- README.md
- rubygems.md
These currently live on [the wiki/wiki](https://github.com/alphagov/wiki/wiki/Gem-guidelines).  This seems like a more appropriate place for them.
/cc @dsingleton
> Pull in rubygems guidelines from wiki/wiki

- ruby.md
- We refer to "surround[ing] the assignment" with (), hence now using
the plural of "parenthesis": parentheses.
- Lowercase "ok" looked weird.
> Fix typos: plurals and uppercase

- ruby-styleguide/rubocop/other-lint.yml
* Made yml consistently use spaces.
* Fixed an error that occurs when parsing the Yaml with Psych:
```
Found a tab character where an intendation space is expected while
scanning a block scalar at line 54 column 16
```
> [remove_tabs_from_yaml] Remove TABs from Yaml

- ruby.md
Remove the recommendation that lines are kept to fewer than 80 characters.
We removed the line length check from Rubocop in govuk-lint PR 7[1] and it
feels as though this Styleguide and the Rubocop rules should be kept in sync.
[1]: https://github.com/alphagov/govuk-lint/pull/7
> Remove line length recommendation from ruby.md

- ruby.md
This was conflicting with earlier advice on spacing around hash braces.
> Spaces hash braces consistently with guide

- pull-requests.md
The pull request guidance is currently very long. It contains useful information, but is too long to point people at; it is basically a wall of text.
This is a first stab at cutting it down to the crucial points so it can be a more useful resource. There is certainly more that could be done but I thought it worth making this first step. Explanation of all changes is in each commit message.
I've discussed my intention to do this offline with @daibach and I think it should probably be him who reviews this. Please note, Dai, that I am on leave from 6th January so won't respond to any comments after that; if you are looking at it after that point please feel free to make any changes you think are appropriate.
> Edit Pull Request styleguide

- ruby.md
There's no cop available to enforce our current "blank line before, nothing after" rule so we can only enforce this using humans.  To reduce the burden we should change our guide to something that is enforcable by a cop (Style/EmptyLinesAroundAccessModifier) and is more in line with the global ruby community reckons expressed in https://github.com/bbatsov/ruby-style-guide#indent-public-private-protected.
Assuming we're happy with this, I'll raise a PR to enable the relevant cop in https://github.com/alphagov/govuk-lint
> Prefer blank lines around access modifiers

- html.md
This article explains why it is best to use the ARIA landmark role
`role=“navigation”` on the `<nav>` tag.
cc. @tombye, @fofr.
> Add a link to a supporting article from Léonie

- ruby.md
I've noticed various styles being used throughout the projects and
wanted to try and settle upon some recognised style for calling methods
with multiple arguments spanning multiple lines. My preferred style is
the one described as `#good`. I know others prefer `#bad`.
My view is the `#good` style apes our guidance for literal arrays and
hashes and adds readability. Often what can happen is those arguments
are indented at the opening paren level and can be missed or obscured
for those of us with 80 (and for some measures greater) char terminals.
If this gets general approval, I'll add a cop to `alphagov/govuk-lint`
and revisit this guidance with a referral to said cop.
> Guidance for calling methods with multiple args

- ruby.md
This cop is disabled in `govuk-lint` since version 0.7.0
> Remove `IfUnlessModifier` from Ruby style guide

- use-of-READMEs.md
Several documents in this repo mandate using soft-tabs with a two-space indent, so it seems only sensible to do it in this file too.
> Replace tab characters with two spaces

- use-of-READMEs.md
This supersedes #87.
In the list of bad examples it wasn't obvious to me that the link to the Smart Answers README was for an old version of the app. The previous wording implied to me that the current version of the Smart Answer README is "bad" when it is not.
Likewise in the list of good examples, it wasn't obvious to me what "modern" Smart Answers meant.
> Clarify wording about Smart Answers in use-of-READMEs.md

- js.md
Updated to reflect @colinrotherham 's changes to enable support for module loaders.
https://github.com/alphagov/govuk_frontend_toolkit/pull/290
(Hopefully in the future we can remove this boilerplate in favour of a proper module system 🙌 )
> Update example for GOVUK modules to be consistent with current codebase

- git.md
While reviewing another PR, I wanted to point someone to the rule I've been taught about avoiding merge commits, as they add noise to the history. I realised it was an unwritten rule, so I'm suggesting to add it here.
> Add guidance about avoiding merge commits

- README.md
- api.md
- css.md
- go.md
- pull-requests.md
- ruby.md
- rubygems.md
- use-of-READMEs.md
- using-rubocop.md
This PR:
- Makes the guides use the words "style guide" consistently (rather than "styleguide")
- Fixes inconsistencies in the headings
> Make guides more consistent

- licensing.md
We made lots of updates a few years ago to make sure everything had Crown Copyright, and most of our repos have licence files, but we don't consistently do this correctly; for example some repositories do not include the title of the licence so you have to read all the text to be sure what it is.
This commit adds a styleguide to clarify what the licence should look like.
> Add licensing styleguide

- rubygems.md
The asciicast.com domain has lapsed, and has been bought by spammers.
Railscasts.com has the cast at the same path with a small addition to
the querystring.
> Change rubygems asciicast link to railscasts

- using-rubocop.md
This commit updates the rubocop style guide with information about the default Jenkins build script automatically running `govuk-lint` if it is present.
> Update rubocop style guide with Jenkins lint info

- use-of-READMEs.md
This commit updates the README guidelines to match current process where we use the GitHub link field to link to the developer docs page for the relevant app.
> Update README guidelines for GitHub link field

- licensing.md
Link to copyright notices is returning a 404. This corrects the link.
[Clickable broken - http://www.copyrightservice.co.uk/copyright/p03_copyright_notice](http://www.copyrightservice.co.uk/copyright/p03_copyright_notice)
[Clickable fixed - http://www.copyrightservice.co.uk/copyright/p03_copyright_notices](http://www.copyrightservice.co.uk/copyright/p03_copyright_notices)
> Fix broken link

- js.md
I thought it pointed to a footnote, but it didn't - so it's just confusing! I assume it slipped in by accident.
> remove stray `§` character
